### ISSUE TITLE
SIGSEGV in Entity::SendMessage.

### ISSUE THREAD

**Issue by Viech** [DaemonDevelopers/CBSE-Toolchain#25]
This occured on Unvanquished's commit 617fe03 using current CBSE-Toolchain master of e850ce4. The signal comes from Thread 2.
	
	Thread 6 (Thread 0x7fffec8a1700 (LWP 27958)):
	#0  0x00007ffff3ce7ead in nanosleep () from /usr/lib/libc.so.6
	No symbol table info available.
	#1  0x00007ffff3ce7d44 in sleep () from /usr/lib/libc.so.6
	No symbol table info available.
	#2  0x000000000044a0b3 in Sys::SignalThread () at /home/eris/src/Unvanquished/src/engine/framework/System.cpp:367
			sigset = {__val = {20487, 0 <repeats 15 times>}}
			sa = {__sigaction_handler = {sa_handler = 0x44abf6 <Sys::SignalHandler(int)>, sa_sigaction = 0x44abf6 <Sys::SignalHandler(int)>}, sa_mask = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x0}
	#3  0x000000000044bb71 in _M_invoke<> (this=<optimized out>) at /usr/include/c++/4.9.2/functional:1700
	No locals.
	#4  operator() (this=<optimized out>) at /usr/include/c++/4.9.2/functional:1688
	No locals.
	#5  std::thread::_Impl<std::_Bind_simple<void (*())()> >::_M_run() (this=<optimized out>) at /usr/include/c++/4.9.2/thread:115
	No locals.
	#6  0x00007ffff44c0df0 in execute_native_thread_routine () from /usr/lib/libstdc++.so.6
	No symbol table info available.
	#7  0x00007ffff3fda374 in start_thread () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#8  0x00007ffff3d1827d in clone () from /usr/lib/libc.so.6
	No symbol table info available.
	
	Thread 5 (Thread 0x7fffebda8700 (LWP 27959)):
	#0  0x00007ffff3fe2add in accept () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#1  0x000000000044a4b1 in Sys::ReadSingletonSocket () at /home/eris/src/Unvanquished/src/engine/framework/System.cpp:245
			sock = <optimized out>
	#2  0x000000000044bb71 in _M_invoke<> (this=<optimized out>) at /usr/include/c++/4.9.2/functional:1700
	No locals.
	#3  operator() (this=<optimized out>) at /usr/include/c++/4.9.2/functional:1688
	No locals.
	#4  std::thread::_Impl<std::_Bind_simple<void (*())()> >::_M_run() (this=<optimized out>) at /usr/include/c++/4.9.2/thread:115
	No locals.
	#5  0x00007ffff44c0df0 in execute_native_thread_routine () from /usr/lib/libstdc++.so.6
	No symbol table info available.
	#6  0x00007ffff3fda374 in start_thread () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#7  0x00007ffff3d1827d in clone () from /usr/lib/libc.so.6
	No symbol table info available.
	
	Thread 4 (Thread 0x7fffbd056700 (LWP 27962)):
	#0  0x00007ffff3d0f4ed in poll () from /usr/lib/libc.so.6
	No symbol table info available.
	#1  0x00007fffbeac08d6 in ?? () from /usr/lib/libasound.so.2
	No symbol table info available.
	#2  0x00007ffff5c6455a in ?? () from /usr/lib/libopenal.so.1
	No symbol table info available.
	#3  0x00007ffff5c6d0d7 in ?? () from /usr/lib/libopenal.so.1
	No symbol table info available.
	#4  0x00007ffff3fda374 in start_thread () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#5  0x00007ffff3d1827d in clone () from /usr/lib/libc.so.6
	No symbol table info available.
	
	Thread 3 (Thread 0x7fffbda64700 (LWP 27966)):
	#0  0x00007ffff3fe2cbd in recvmsg () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#1  0x00007fffc7171d8d in NaClReceiveDatagram (handle=37, message=0x7fffbda63bd0, flags=0) at /home/eris/src/Unvanquished/src/libs/nacl/native_client/src/shared/imc/linux/nacl_imc.cc:168
			msg = {msg_name = 0x0, msg_namelen = 0, msg_iov = 0x7fffbda63bf0, msg_iovlen = 2, msg_control = 0x7fffbda63b00, msg_controllen = 48, msg_flags = 0}
			buf = "\000\000\000\000\000\000\000\000{\000\000\000|\000\000\000\004\000\000\000\000\000\000\000 \000\000\270\377\177\000\000\370\000\002", '\000' <repeats 12 times>
			count = <optimized out>
	#2  0x00007fffc7163ecf in IPC::InternalRecvMsg (handle=37, reader=...) at /home/eris/src/Unvanquished/src/common/IPC/Primitives.cpp:374
			recvBuffer = std::unique_ptr<char> containing 0x7fffb80c4b60 "H\b"
			internalHdr = {h = {xfer_protocol_version = 4, descriptor_data_bytes = 0}, pad = "p\v\210\271\377\177\000"}
			desc_ptr = <optimized out>
			hdr = {iov = 0x7fffbda63bf0, iov_length = 2, handles = 0x7fffbda63c10, handle_count = 8, flags = 0}
			iov = {{base = 0x7fffbda63bc0, length = 16}, {base = 0x7fffb80c4b60, length = 131320}}
			h = {-1, -1, -1, -1, -1, -1, -1, -1}
			result = <optimized out>
			desc_end = <optimized out>
			handle_index = <optimized out>
	#3  0x00007fffc716421a in IPC::Socket::RecvMsg (this=this@entry=0x7fffc86e7bc0 <VM::rootChannel>) at /home/eris/src/Unvanquished/src/common/IPC/Primitives.cpp:457
			out = {data = std::vector of length 0, capacity 0, handles = std::vector of length 0, capacity 0, pos = 0, handles_pos = 0}
	#4  0x00007fffc71397ff in RecvMsg (this=0x7fffc86e7bc0 <VM::rootChannel>) at /home/eris/src/Unvanquished/src/common/IPC/Channel.h:111
	No locals.
	#5  CommonInit (rootSocket=<optimized out>) at /home/eris/src/Unvanquished/src/gamelogic/shared/VMMain.cpp:61
			reader = {data = std::vector of length 0, capacity 0, handles = std::vector of length 0, capacity 0, pos = 0, handles_pos = 0}
			id = <optimized out>
			writer = {data = std::vector of length 4, capacity 4 = {1 '\001', 0 '\000', 0 '\000', 0 '\000'}, handles = std::vector of length 0, capacity 0}
	#6  0x00007fffc7139aae in vmMain (rootSocket=<optimized out>) at /home/eris/src/Unvanquished/src/gamelogic/shared/VMMain.cpp:104
	No locals.
	#7  0x000000000044da53 in operator() (__closure=0x6937978) at /home/eris/src/Unvanquished/src/engine/framework/VirtualMachine.cpp:351
			inProcess = @0x137be50: {thread = {_M_id = {_M_thread = 140736375179008}}, mutex = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}, condition = {_M_cond = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}, sharedLib = {handle = 0x6936820}, running = true}
			vmSocketArg = 37
			vmMain = 0x7fffc7139aa4 <vmMain(Sys::OSHandle)>
	#8  _M_invoke<> (this=0x6937978) at /usr/include/c++/4.9.2/functional:1700
	No locals.
	#9  operator() (this=0x6937978) at /usr/include/c++/4.9.2/functional:1688
	No locals.
	#10 std::thread::_Impl<std::_Bind_simple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::StringRef, VM::VMBase::InProcessInfo&)::<lambda()>()> >::_M_run(void) (this=0x6937960) at /usr/include/c++/4.9.2/thread:115
	No locals.
	#11 0x00007ffff44c0df0 in execute_native_thread_routine () from /usr/lib/libstdc++.so.6
	No symbol table info available.
	#12 0x00007ffff3fda374 in start_thread () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#13 0x00007ffff3d1827d in clone () from /usr/lib/libc.so.6
	No symbol table info available.
	
	Thread 2 (Thread 0x7fffc5f42700 (LWP 27965)):
	#0  0x00007fffc62921f0 in vtable for VMCvarProxy () from /home/eris/src/Unvanquished/build/sgame-native-dll.so
	No symbol table info available.
	#1  0x00007fffc5fc44e9 in Entity::SendMessage (this=<optimized out>, msg=msg@entry=0, data=data@entry=0x0) at /home/eris/src/Unvanquished/src/gamelogic/sgame/backend/CBSEBackend.cpp:31
			handler = <optimized out>
	#2  0x00007fffc5fc450f in Entity::PrepareNetCode (this=<optimized out>) at /home/eris/src/Unvanquished/src/gamelogic/sgame/backend/CBSEBackend.cpp:42
	No locals.
	#3  0x00007fffc5f91728 in G_RunFrame (levelTime=-1317034096) at /home/eris/src/Unvanquished/src/gamelogic/sgame/sg_main.cpp:2974
			ptime3000 = 0
	#4  0x00007fffc5f5f1c9 in operator() (levelTime=<optimized out>, __closure=0x7fffc5f41d7f) at /home/eris/src/Unvanquished/src/gamelogic/sgame/sg_api.cpp:118
	No locals.
	#5  Util::apply_impl<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)>, std::tuple<int&&>, 0ul>(<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c172>, <unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c283>, Util::seq<0ul>) (func=func@entry=<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c172>, tuple=tuple@entry=<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c283>) at /home/eris/src/Unvanquished/src/common/Util.h:103
	No locals.
	#6  0x00007fffc5f5f1d9 in Util::apply<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)>, std::tuple<int&&> >(<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c2c6>, <unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c2fb>) (func=func@entry=<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c2c6>, tuple=tuple@entry=<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x4c2fb>) at /home/eris/src/Unvanquished/src/common/Util.h:108
	No locals.
	#7  0x00007fffc5f60010 in IPC::detail::HandleMsg<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)>, IPC::Message<IPC::Id<0u, 9u>, int>, IPC::Reply<> >(IPC::Channel &, IPC::SyncMessage<IPC::Message<IPC::Id<0u, 9u>, int>, IPC::Reply<> >, Util::Reader, <unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x5933e>) (channel=..., reader=..., func=func@entry=<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x5933e>) at /home/eris/src/Unvanquished/src/common/IPC/Channel.h:217
			inputs = std::tuple containing = {[1] = 295350}
			oldSync = false
			oldAsync = false
			writer = {data = std::vector of length 4, capacity 4 = {-32 '\340', 36 '$', -9 '\367', -80 '\260'}, handles = std::vector of length 0, capacity 0}
	#8  0x00007fffc5f6013b in IPC::HandleMsg<IPC::SyncMessage<IPC::Message<IPC::Id<0u, 9u>, int> >, VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)> >(IPC::Channel &, Util::Reader, <unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x59d26>) (channel=..., reader=..., func=func@entry=<unknown type in /home/eris/src/Unvanquished/build/sgame-native-dll.so, CU 0xb982, DIE 0x59d26>) at /home/eris/src/Unvanquished/src/common/IPC/Channel.h:241
	No locals.
	#9  0x00007fffc5f60dfd in VM::VMHandleSyscall (id=<optimized out>, reader=...) at /home/eris/src/Unvanquished/src/gamelogic/sgame/sg_api.cpp:119
			major = <optimized out>
			minor = <optimized out>
	#10 0x00007fffc5ffd965 in CommonInit (rootSocket=<optimized out>) at /home/eris/src/Unvanquished/src/gamelogic/shared/VMMain.cpp:66
			reader = {data = std::vector of length 0, capacity 0, handles = std::vector of length 0, capacity 0, pos = 4, handles_pos = 0}
			id = <optimized out>
			writer = {data = std::vector of length 4, capacity 4 = {1 '\001', 0 '\000', 0 '\000', 0 '\000'}, handles = std::vector of length 0, capacity 0}
	#11 0x00007fffc5ffdb36 in vmMain (rootSocket=<optimized out>) at /home/eris/src/Unvanquished/src/gamelogic/shared/VMMain.cpp:104
	No locals.
	#12 0x000000000044da53 in operator() (__closure=0xcb2bc38) at /home/eris/src/Unvanquished/src/engine/framework/VirtualMachine.cpp:351
			inProcess = @0x19dd490: {thread = {_M_id = {_M_thread = 140736514500352}}, mutex = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}, condition = {_M_cond = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}, sharedLib = {handle = 0xdfbc490}, running = true}
			vmSocketArg = 67
			vmMain = 0x7fffc5ffdb2c <vmMain(Sys::OSHandle)>
	#13 _M_invoke<> (this=0xcb2bc38) at /usr/include/c++/4.9.2/functional:1700
	No locals.
	#14 operator() (this=0xcb2bc38) at /usr/include/c++/4.9.2/functional:1688
	No locals.
	#15 std::thread::_Impl<std::_Bind_simple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::StringRef, VM::VMBase::InProcessInfo&)::<lambda()>()> >::_M_run(void) (this=0xcb2bc20) at /usr/include/c++/4.9.2/thread:115
	No locals.
	#16 0x00007ffff44c0df0 in execute_native_thread_routine () from /usr/lib/libstdc++.so.6
	No symbol table info available.
	#17 0x00007ffff3fda374 in start_thread () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#18 0x00007ffff3d1827d in clone () from /usr/lib/libc.so.6
	No symbol table info available.
	
	Thread 1 (Thread 0x7ffff7fa6780 (LWP 27954)):
	#0  0x00007ffff3fe2cbd in recvmsg () from /usr/lib/libpthread.so.0
	No symbol table info available.
	#1  0x000000000066bd83 in NaClReceiveDatagram (handle=66, message=0x7fffffffe330, flags=0) at /home/eris/src/Unvanquished/src/libs/nacl/native_client/src/shared/imc/linux/nacl_imc.cc:168
			msg = {msg_name = 0x0, msg_namelen = 0, msg_iov = 0x7fffffffe350, msg_iovlen = 2, msg_control = 0x7fffffffe270, msg_controllen = 48, msg_flags = 0}
			buf = "\000\000\000\000\000\000\000\000{\000\000\000|\000\000\000\000\000\000\000\001\000\000\000\000\334\374\363\377\177\000\000\370\000\002\000\000\000\000\000(\261Z\000\000\000\000"
			count = <optimized out>
	#2  0x0000000000490f43 in IPC::InternalRecvMsg (handle=66, reader=...) at /home/eris/src/Unvanquished/src/common/IPC/Primitives.cpp:374
			internalHdr = {h = {xfer_protocol_version = 3552632321, descriptor_data_bytes = 0}, pad = "\000\000\000\000\000\000\000"}
			desc_ptr = <optimized out>
			hdr = {iov = 0x7fffffffe350, iov_length = 2, handles = 0x7fffffffe370, handle_count = 8, flags = 0}
			iov = {{base = 0x7fffffffe320, length = 16}, {base = 0x3d2b0150, length = 131320}}
			h = {-1, -1, -1, -1, -1, -1, -1, -1}
			result = <optimized out>
			desc_end = <optimized out>
			handle_index = <optimized out>
	#3  0x000000000049127c in IPC::Socket::RecvMsg (this=0x19dd500 <gvm+128>) at /home/eris/src/Unvanquished/src/common/IPC/Primitives.cpp:457
			out = {data = std::vector of length 0, capacity 0, handles = std::vector of length 0, capacity 0, pos = 0, handles_pos = 0}
	#4  0x0000000000504b54 in RecvMsg (this=0x19dd500 <gvm+128>) at /home/eris/src/Unvanquished/src/common/IPC/Channel.h:111
	No locals.
	#5  RecvReplyMsg (this=0x19dd500 <gvm+128>) at /home/eris/src/Unvanquished/src/common/IPC/Channel.h:121
			reader = {data = std::vector of length 0, capacity 0, handles = std::vector of length 0, capacity 0, pos = 0, handles_pos = 0}
			id = <optimized out>
	#6  IPC::detail::SendMsg<void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, int>, IPC::Reply<> >, int&>(int&)::{lambda(unsigned int, Util::Reader)#1}&, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, int>, IPC::Reply<><int&> > (channel=..., messageHandler=...) at /home/eris/src/Unvanquished/src/common/IPC/Channel.h:168
			reader = {data = std::vector of length 0, capacity 0, handles = std::vector of length 0, capacity 0, pos = 0, handles_pos = 0}
			id = <optimized out>
			writer = {data = std::vector of length 8, capacity 8 = {9 '\t', 0 '\000', 0 '\000', 0 '\000', -74 '\266', -127 '\201', 4 '\004', 0 '\000'}, handles = std::vector of length 0, capacity 0}
	#7  0x0000000000504da3 in _ZN3IPC7SendMsgINS_11SyncMessageINS_7MessageINS_2IdILt0ELt9EEEIiEEENS_5ReplyIIEEEEEZN2VM6VMBase7SendMsgIS8_IRiEEEvDpOT0_EUljN4Util6ReaderEE_ISC_EEEvRNS_7ChannelEOT0_DpOT1_ (channel=..., messageHandler=messageHandler@entry=<unknown type in /home/eris/src/Unvanquished/build/daemon, CU 0x814c0b, DIE 0x976424>) at /home/eris/src/Unvanquished/src/common/IPC/Channel.h:234
	No locals.
	#8  0x00000000005aba0b in SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<0u, 9u>, int> >, int&> (this=0x19dd480 <gvm>) at /home/eris/src/Unvanquished/src/engine/framework/VirtualMachine.h:134
	No locals.
	#9  GameVM::GameRunFrame (this=this@entry=0x19dd480 <gvm>, levelTime=295350) at /home/eris/src/Unvanquished/src/engine/server/sv_sgame.cpp:498
	No locals.
	#10 0x00000000005b32a7 in SV_Frame (msec=msec@entry=10) at /home/eris/src/Unvanquished/src/engine/server/sv_main.cpp:1351
			frameMsec = 25
			startTime = 0
			mapname = "\000\004\000\000`\260\004\000p\362B\000\000\000\000\000\200Ê\000\000\000\000\000\001\004\000\000\366\377\377\377\001\000\000\000\000\000\000\000\360\343\377\377\377\177\000\000\200\372\266\001\000\000\000\000\n\000\000\000\000\000\000"
			frameStartTime = 307296
			end = 307285
			frameEndTime = <optimized out>
			start = 307296
	#11 0x0000000000456859 in Com_Frame () at /home/eris/src/Unvanquished/src/engine/qcommon/common.cpp:2005
			msec = 10
			timeBeforeEvents = 0
			timeBeforeClient = 0
			timeAfter = 0
			timeBeforeFirstEvents = 0
			timeBeforeServer = 0
			minMsec = 8
			lastTime = 307295
			watchdogTime = 0
			watchWarn = false
	#12 0x000000000044b900 in main (argc=<optimized out>, argv=<optimized out>) at /home/eris/src/Unvanquished/src/engine/framework/System.cpp:690
	No locals.

**Comment by Kangz** [comment]
Any idea how to repro?

**Comment by Viech** [comment]
This appeared to happen unconditionally the first time it occured (which is the log I posted), the second time was after deleting bots if I remember correctly. There were also bots in the first game.
